# This is a config for E2B sandbox template.
# You can use template ID (wzjo6zi7og72v6qenjup) or template name (BuildUi) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("BuildUi") # Sync sandbox
# sandbox = await AsyncSandbox.create("BuildUi") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('BuildUi')

team_id = "e08e4155-5cdc-443a-a834-2804d05a80e9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "BuildUi"
template_id = "wzjo6zi7og72v6qenjup"
